image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      touch /tmp/.npm-lock
      npm install
      rm /tmp/.npm-lock
    command: |
      echo "Starting Ambianic PWA in dev mode"
      npm run serve
  - init: |
      sleep 1 && while [ -f /tmp/.npm-lock ]; do sleep 1; done
    command: |
      echo "Waiting for npm install to finish"
      gp await-port 8080
      echo "Starting Ambianic PWA testsuite"
      npm run test

vscode:
  extensions:
    - octref.vetur@0.31.3:QHyAEoimIBiRDoL6WtEoRg==

ports:
  - port: 8080

github:
  prebuilds:
    addComment: true

