image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm install && npm install cypress
    command: |
      echo "Starting Ambianic PWA in dev mode"
      npm run serve
  - command: |
      echo "Waiting for Ambianic PWA web service to become avaibale"
      gp await-port 8080
      echo "Starting Ambianic PWA testsuite"
      npm run test

vscode:
  extensions:
    - octref.vetur@0.31.3:QHyAEoimIBiRDoL6WtEoRg==

ports:
  - port: 8080

github:
  prebuilds:
    addComment: true

