image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm install && npm audit fix
    command: |
      echo "Starting Ambianic PWA in dev mode"
      npm run serve
  - init: npm install && npm install cypress && npm audit fix && npm run build
    command: |
      echo "Starting Ambianic PWA testsuite"
      npm run test

vscode:
  extensions:
    - octref.vetur@0.31.3:QHyAEoimIBiRDoL6WtEoRg==

ports:
  - port: 8080

github:
  prebuilds:
    addComment: true
