coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0%
        base: auto
        flags:
          - unit
        paths:
          - "src"
        run: pwd
        # advanced
        # branches:
        #  - master
        if_not_found: error
        if_ci_failed: error
        informational: False
        only_pulls: false