# This is a basic workflow to help you get started with Actions

name: Lighthouse CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job
  lighthouse:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1

    - name: NPM install and Build
      run: |
        npm i
        npm run build

    - name: Waiting for 200 from the Netlify Preview
      uses: jakepartusch/wait-for-netlify-action@v1
      id: waitFor200
      with:
        site_name: "happy-franklin-69b6d4"

    # lighthouse localhost test
    - name: Lighthouse CI
      run: |
        npm install -g @lhci/cli@0.3.x
        lhci autorun --config=.github/lighthouse/lighthouserc.json
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

    # runs the lighthouse action (deployed)
    - name: Lighthouse CI Action
      uses: treosh/lighthouse-ci-action@v2
      with:
        urls: |
          $DEPLOY_URL
        budgetPath: '.github/lighthouse/budget.json' # test performance budgets
        configPath: '.github/lighthouse/lighthouserc.json'
        # Path to a LHCI lighthouserc.json file
        # Opt-out of saving Lighthouse results as an action artifacts
        uploadArtifacts: false
        # Number of runs to do per URL
        serverBaseUrl: ${{ secrets.LHCI_SERVER_URL }}
        serverToken: ${{ secrets.LHCI_SERVER_TOKEN }}
      env:
        DEPLOY_URL: ${{ steps.waitFor200.outputs.url }}

