name: CI for Ambianic UI 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm version
        npm install -g npm
        npm version
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: End-to-end tests with Cypress
      uses: cypress-io/github-action@v1
      with: 
        start: npm run serve
        record: true
        wait-on: 'http://localhost:8080'
      env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Codecov.io
      uses: codecov/codecov-action@v1
      with:
        # token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        file: ./coverage/coverage-final.json # optional
        flags: pwa-tests # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
    - name: Semantic Release
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Run a one-line script
      run: echo Semantic release flow completed
