name: CI for Ambianic UI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install npm
      run: |
        npm version
        npm ci
      env:
        CI: true

    - name: Test Suite
      uses: cypress-io/github-action@v1
      with:
        start: npm run serve
        record: false # cypress.io free recording limit exceeded
        wait-on: 'http://localhost:8080'
        command: npm test
      env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    

    - name: Code Coverage Report
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        file: |
          ./coverage/coverage-final.json
          ./coverage/jest/coverage-final.json
        fail_ci_if_error: true # optional (default = false)
    
    - name: Upload Artifact
      uses: actions/upload-artifact@master
        with:
          name: Ambianic-UI
          path: /home/runner/work/ambianic-ui/ambianic-ui